import pyodide

from importlib.metadata import version

from pygments.formatters import HtmlFormatter

header = f"""/**
 * Generated by Pygments v{version("Pygments")} on Pyodide v{pyodide.__version__}
 */
"""
header + HtmlFormatter().get_style_defs('.document')
